<div class="modal fade" id="entregarRepuesto">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" title="Cerrar">&times;</button>
                <h4 class="modal-title">Entregar Repuesto</h4>
            </div>
            <div class="modal-body">
                <form>
                    <input type="hidden" id="id_entregarRepuesto">    
                    <input type="hidden" id="estado_nota" value="2">
                    <div class="form-group">
                        <strong>Fecha de entrega: </strong><br> 
                        <input class="form-control" required type="date" id="fechaEntrega">
                         </div>  
                    <input class="btn btn-primary" id="btnentregar" type="button" value="Entregar">
                    <input class="btn btn-primary pull-right" type="button" data-dismiss="modal" value="Cancelar">
                </form>
            </div>
        </div>
    </div>
</div>