<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" id="selectRepuesto">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" title="Cerrar">&times;</button>
                <h4 class="modal-title">Seleccionar repuesto</h4>
            </div>
            <div class="modal-body">
                <table class="table">
                    <tr>
                        <th>Id</th>
                        <th>Descripción</th>
                        <th>Detalle      </th>
                        <th>Precio unitario</th>
                        <th>Stock</th>
                        <th>Cantidad</th>
                        <th>Opciones</th>
                    </tr>
                    <?php for($i=0; $i<count($repuestos); $i++){ $rs = $repuestos[$i]; ?>
                    <tr>
                        <td><?php echo $rs['id_repuesto']; ?></td>
                        
                        <td><?php echo $rs['descripcion']; ?></td>
                        <td><?php echo $rs['detalle'];         ?></td>
                        <td><?php echo $rs['precio_unitario']; ?></td>
                        <td><?php echo $rs['stock']; ?></td>
                        <td><input type="number" placeholder="Cantidad" maxlength="1" min="1" max="<?php echo $rs['stock']; ?>" autofocus class="form-control key"></td>
                        <td>
                            <button type="button" class="btn btn-default glyphicon glyphicon-check" onclick="addRepuesto(this);"></button>
                            <button class=" btn btn-default glyphicon glyphicon-trash" onclick="quitar(this, <?php echo $rs['id_repuesto']; ?>);"></button>
                        </td>
                    </tr>
                    <?php } ?>

                </table>
                
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <button type="button" class="btn btn-default" data-dismiss="modal" title="Aceptar">Aceptar</button>
                </div>
            </div>
        </div>
    </div>
</div>