<div class="modal fade" id="nuevoRepuesto">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        title="Cerrar">&times;</button>
                <h4 class="modal-title">Agregar Repuesto</h4>
            </div>
            <div class="modal-body">
                <form id="formNuevoRepuesto" action="../controllers/almacen/addAlmacen.php" method="post">
                    <div class="form-group">
                    <select class="form-control" required name="tipo" id="tipo">
                            <option value="">seleccione tipo de repuesto</option>
                            <option value="1">Original</option>
                            <option value="2">Generico</option>
                            <option value="3">Oportunidad</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="descripcion" id="descripcion" cols="5" rows="3" maxlength="55" onkeypress="return combinado(event)" required placeholder="Descripción"></textarea>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" name="detalle" id="detalle" cols="5" rows="3" maxlength="55" onkeypress="return combinado(event)" required placeholder="Detalle"></textarea>
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="number" name="precio_unitario" id="precio_unitario" required placeholder="Precio unitario" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="text" name="stock" id="stock" maxlength="3" onkeypress="return soloNumero(event)" required placeholder="Cantidad en Stock" autocomplete="off">
                    </div>
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>