<div class="modal fade" id="editCliente">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" title="Cerrar">&times;</button>
                <h4 class="modal-title">Editar cliente</h4>
            </div>
            <div class="modal-body">
                <form id="formEditCliente" action="../controllers/clientes/editCliente.php" method="post">
                    <input type="hidden" name="id_cliente" id="id_cliente">
                    
                    <div class="form-group">
                        <input class="form-control" type="text" name="new_razon" id="new_razon" onkeypress="return combinado(event)" required autocomplete="off">
                    </div>

                    <div class="form-group">
                        <div class="col-md-4">
                            <!--TIPO DE RIF-->
                            <select class="form-control" name="new_tipo_rif" id="new_tipo_rif">
                                <option value="0">Tipo de RIF</option>
                                <option value="1">Venezolano</option>
                                <option value="2">Juridico</option>
                                <option value="3">Gubernamental</option>
                                <option value="4">Extranjero</option>
                                <option value="5">Pasaporte</option>
                            </select>
                        </div>

                        <!--NUMERO DE RIF-->
                        <div class="col-md-4">
                            <input class="form-control" type="text" name="new_Nrif" id="new_Nrif" maxlength="10" minlength="6"  onkeypress=" return soloNumero(event)" onblur="limpiaNRif()" required autocomplete="off">
                        </div>
                    </div>

                    <div class="form-group" style="padding-top: 8%;">
                        <input class="form-control" type="email" name="new_correo" id="new_correo" required autocomplete="off">
                    </div>
                    
                    <div class="form-group">
                        <textarea class="form-control" type="text" name="new_direccion" id="new_direccion" required autocomplete="off"></textarea>
                    </div>

                    <div class="form-group">
                        <input class="form-control" type="text" name="new_telefono" id="new_telefono" maxlength="12" maxlength="10" onkeypress="return soloNumero(event)" onblur="limpiaNtelf()" required autocomplete="off">
                    </div>
                    
                    <input class="btn btn-primary" type="submit" value="Guardar">
                </form>
            </div>
        </div>
    </div>
</div>     